### ISSUE TITLE
Nesprávné řazení souborů

### ISSUE THREAD

**Issue by nalvid** [triorg/asol#1]
Zřejmě se špatně zařazují soubory z počátku a konce roku, příklad výstupu:

```shell
{"source": "source\\2021-01-01_1.json", "target": "target\\2021\\W53\\01-01_1.json"}
                                                           ^^^^^^^^^ Má být 2020W53         
```

viz https://www.calendar-week.org/calendar-weeks/2020/cw-53

**Comment by triopium** [comment]
Děkuji. Dám tam check jestli je číslo týdne pro dané datum větší než číslo následujícího týdne.
Pokud ano snížím číslo roku cílového adresáře o jednotku.

**Comment by nalvid** [comment]
Řešení máte ve standardní knihovně Pythonu. Jste dokonce skoro hotov bez práce viz https://github.com/triorg/asol/blob/6d466dcb5cfb9b3c5aa1affeebeb8dc7a0e597a0/asol/runner.py#LL111C17-L111C38.
Mrkněte do dokumentace funkce `isocalendar()` co vrací.

**Comment by triopium** [comment]
Stačí dát year=str(date.isocalendar()[0])
děkuji

**Comment by nalvid** [comment]
Jo, možná ještě zkráceně najednou, protože se vrací `NamedTuple`:

```python
from datetime import date
year, week, _ = date(2021, 1, 1).isocalendar()
year, week
(2020, 53)
```
